name = "daylo-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "daylo-db"
database_id = "f0ead8c8-6d5d-4294-9d2b-795ab2892b4a"

[vars]
JWT_SECRET = "QbbrocAYhx8Dq5UW640WehcIbtUBcDjl5zMIycpp70c="
